export const CUSTOM_PROVIDER_TOKENS = {
  PASSWORD_HASHING_SERVICE: 'HASHING_ABSTRACT_SERVICE',
  CACHE: {
    REDIS_SERVICE: 'REDIS_CLIENT_SERVICE',
    REDIS_CACHE_CLIENT: 'REDIS_CACHE_CLIENT',
  },
};
